import { create } from 'zustand'
import { devtools } from 'zustand/middleware'
import type { CameraInstance, CameraInstanceCreatePayload, CameraInstanceUpdatePayload } from '../../api/cameraInstances.types'
import client from '../../api/client'
import type { CameraInstanceStoreState, CameraRecord } from './types'
import { filterCameras, withTrackingPatch } from './helpers'
import { buildCreatePayload, buildUpdatePayload, errorMessage } from './payloadBuilders'

export const useCameraInstanceStore = create<CameraInstanceStoreState>()(
  devtools(
    (set, get) => ({
      clientIds: [],
      cameraRecords: {},
      deletedCameras: new Set(),
      isLoading: false,
      loadError: null,

      // ── Derived selectors ───────────────────────────────────────────────────

      getCamerasToPost: () => {
        const { clientIds, cameraRecords } = get()
        return filterCameras(clientIds, cameraRecords, true)
      },

      getCamerasToPut: () => {
        const { clientIds, cameraRecords } = get()
        return filterCameras(clientIds, cameraRecords, false)
      },

      getIsDirty: () => {
        const { clientIds, cameraRecords, deletedCameras } = get()
        return deletedCameras.size > 0 || clientIds.some((id) => cameraRecords[id]?.tracking.isDirty)
      },

      // ── loadCameras ─────────────────────────────────────────────────────────

      loadCameras: async (projectId) => {
        set({ isLoading: true, loadError: null })
        try {
          console.log("Fetching project cameras")
          const res = await client.get<CameraInstance[]>(`/projects/${projectId}/cameras`)
          console.log("Project cameras fetched", res.data)

          const cameraRecords: Record<string, CameraRecord> = {}
          const clientIds: string[] = []

          for (const camera of res.data) {
            clientIds.push(camera.uid)
            cameraRecords[camera.uid] = {
              camera,
              tracking: { isNew: false, isDirty: false, status: 'saved', error: null },
            }
          }

          set({ clientIds, cameraRecords, deletedCameras: new Set(), isLoading: false })
        } catch (e) {
          const msg = e instanceof Error ? e.message : 'Failed to load cameras'
          set({ loadError: msg, isLoading: false })
        }
      },

      // ── addCamera ───────────────────────────────────────────────────────────
      // clientId must be set on camera before calling — generated by caller
      // Store uses camera.uid as the stable key throughout the session

      addCamera: (camera) => {
        const clientId = camera.uid
        if (!clientId) {
          console.error('addCamera: camera.uid is required')
          return ''
        }
        set((s) => ({
          clientIds: [...s.clientIds, clientId],
          cameraRecords: {
            ...s.cameraRecords,
            [clientId]: {
              camera,
              tracking: { isNew: true, isDirty: true, status: 'pending', error: null },
            },
          },
        }))
        return clientId
      },

      // ── updateCamera ────────────────────────────────────────────────────────

      updateCamera: (clientId, patch) => {
        set((s) => {
          const record = s.cameraRecords[clientId]
          if (!record) {
            console.warn(`updateCamera: unknown clientId "${clientId}"`)
            return s
          }
          const wasSaving = record.tracking.status === 'saving'
          return {
            cameraRecords: {
              ...s.cameraRecords,
              [clientId]: {
                camera: { ...record.camera, ...patch },
                tracking: {
                  ...record.tracking,
                  isDirty: true,
                  // Don't revert status back to pending if saving — let
                  // markSaved/markFailed handle that transition
                  status: wasSaving ? 'saving' : 'pending',
                },
              },
            },
          }
        })
      },

      // ── removeCamera ────────────────────────────────────────────────────────

      removeCamera: (clientId) => {
        set((s) => {
          const record = s.cameraRecords[clientId]
          if (!record) return s

          // eslint-disable-next-line @typescript-eslint/no-unused-vars
          const { [clientId]: _removed, ...remainingRecords } = s.cameraRecords
          const remainingIds = s.clientIds.filter((id) => id !== clientId)

          if (record.tracking.isNew) {
            // Never saved — drop entirely, no server call needed
            return { clientIds: remainingIds, cameraRecords: remainingRecords }
          }

          // Saved on server — queue clientId for DELETE
          const deletedCameras = new Set(s.deletedCameras)
          deletedCameras.add(clientId)
          return { clientIds: remainingIds, cameraRecords: remainingRecords, deletedCameras }
        })
      },

      // ── markSaving ──────────────────────────────────────────────────────────

      markSaving: (clientId) => {
        set((s) => {
          const updated = withTrackingPatch(s.cameraRecords, clientId, {
            isDirty: false,   // exclude from next Save press
            status: 'saving',
            error: null,
          })
          return updated ? { cameraRecords: updated } : s
        })
      },

      // ── markSaved ───────────────────────────────────────────────────────────

      markSaved: (clientId) => {
        set((s) => {
          const updated = withTrackingPatch(s.cameraRecords, clientId, {
            isNew: false,     // camera now exists on server
            isDirty: false,
            status: 'saved',
            error: null,
          })
          return updated ? { cameraRecords: updated } : s
        })
      },

      // ── markFailed ──────────────────────────────────────────────────────────

      markFailed: (clientId, error) => {
        set((s) => {
          const updated = withTrackingPatch(s.cameraRecords, clientId, {
            isDirty: true,    // re-include in next Save press
            status: 'failed',
            error,
          })
          return updated ? { cameraRecords: updated } : s
        })
      },

      // ── markDeleted ─────────────────────────────────────────────────────────

      markDeleted: (clientId) => {
        set((s) => {
          const deletedCameras = new Set(s.deletedCameras)
          deletedCameras.delete(clientId)
          return { deletedCameras }
        })
      },

      // ── saveAll ─────────────────────────────────────────────────────────────

      saveAll: async (projectId) => {
        const store = get()
        const toPost = store.getCamerasToPost()
        const toPut = store.getCamerasToPut()
        const toDelete = [...store.deletedCameras]  // Set → array of clientIds

        // Mark all in-flight cameras as saving before firing requests
        // This prevents a second Save press from re-sending them
        for (const record of [...toPost, ...toPut]) {
          store.markSaving(record.camera.uid)
        }

        // Fire all three operation types in parallel
        await Promise.allSettled([

          // POST — new cameras (isNew: true)
          ...toPost.map(async (record) => {
            const clientId = record.camera.uid
            try {
              const payload: CameraInstanceCreatePayload = buildCreatePayload(record.camera)
              console.log("Sending post req for camera addition", payload.uid)
              await client.post<CameraInstance>(`/projects/${projectId}/cameras`, payload)
              get().markSaved(clientId)
            } catch (e) {
              get().markFailed(clientId, errorMessage(e))
            }
          }),

          // PUT — updated cameras (isNew: false) — routed by clientId on server
          ...toPut.map(async (record) => {
            const clientId = record.camera.uid
            try {
              const payload: CameraInstanceUpdatePayload = buildUpdatePayload(record.camera)
              await client.put(`/projects/${projectId}/cameras/${clientId}`, payload)
              get().markSaved(clientId)
            } catch (e) {
              get().markFailed(clientId, errorMessage(e))
            }
          }),

          // DELETE — removed cameras — routed by clientId on server
          ...toDelete.map(async (clientId) => {
            try {
              await client.delete(`/projects/${projectId}/cameras/${clientId}`)
              get().markDeleted(clientId)
            } catch (e) {
              // markDeleted not called — clientId stays in deletedCameras for retry
              console.error(`DELETE failed for camera ${clientId}:`, e)
            }
          }),
        ])
      },
    }),
    { name: 'CameraInstanceStore' },
  ),
)
