---
id: 9f2a8c69-7a21-4962-84a8-4232ed4a2f26
---
flowchart TD
    Root([App Component]) --> Router[BrowserRouter]
    Router --> Routes{React Routes}

    %% Public Routes Logic
    Routes -->|Layout Wrapper| PublicOnlyGroup[[PublicOnlyRoute Component]]
    PublicOnlyGroup -.->|Redirects to '/' if logged in| PublicOnlyGroup
    PublicOnlyGroup -->|path: /login| LoginPage(LoginPage)
    PublicOnlyGroup -->|path: /accept-invite| AcceptInvitePage(AcceptInvitePage)

    %% Protected Routes Logic
    Routes -->|Layout Wrapper| ProtectedGroup[[ProtectedRoute Component]]
    ProtectedGroup -.->|Redirects to '/login' if unauthenticated| ProtectedGroup
    ProtectedGroup -->|path: /| DashboardPage(DashboardPage)
    ProtectedGroup -->|path: /admin/manage| AdminPage(AdminPage)
    ProtectedGroup -->|path: /admin/manage/cameras| AdminCamerasPage(AdminCamerasPage)
    ProtectedGroup -->|path: /admin/manage/cameras/:id| AdminCameraEditPage(AdminCameraEditPage)
    ProtectedGroup -->|path: /project/manage/:id| ProjectManagePage(ProjectManagePage)

    %% Fallback
    Routes -->|path: *| FallbackNavigate([Navigate to='/'])