"""M1.5 seed script. Inserts one test document of each Beanie model (User, InviteToken, CameraModel, Project, Camera, Zone) into MongoDB. Run: uv run python scripts/seed.py from packages/backend."""

import asyncio
import hashlib
import os
import sys
from datetime import datetime, timedelta, timezone

# Allow imports from the app package
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import motor.motor_asyncio
from beanie import init_beanie

from app.core.config import settings
from app.models.camera import Camera
from app.models.camera_model import CameraModel, CameraType, LensType, SensorType
from app.models.invite_token import InviteToken
from app.models.project import Project
from app.models.user import User, SystemRole
from app.models.zone import Zone, ZoneType


async def seed() -> None:
    client = motor.motor_asyncio.AsyncIOMotorClient(settings.MONGO_URI)
    db = client.get_default_database()
    await init_beanie(
        database=db,
        document_models=[User, InviteToken, CameraModel, Project, Camera, Zone],
    )

    # 1. User
    user = User(
        email="seed@example.com",
        full_name="Seed User",
        hashed_password="$2b$12$placeholder_hash",
        system_role=SystemRole.admin,
    )
    await user.insert()
    print(f"[+] User:           {user.id}  ({user.email})")

    # 2. InviteToken
    raw_token = "seed-test-token-abc123"
    token_hash = hashlib.sha256(raw_token.encode()).hexdigest()
    invite = InviteToken(
        token_hash=token_hash,
        email="newuser@example.com",
        invited_by=user,
        expires_at=datetime.now(timezone.utc) + timedelta(hours=settings.INVITE_TOKEN_TTL_HOURS),
    )
    await invite.insert()
    print(f"[+] InviteToken:    {invite.id}")

    # 3. CameraModel
    cam_model = CameraModel(
        name="Main Entrance Camera",
        manufacturer="Hikvision",
        model_number="DS-2CD2T47G2-L",
        camera_type=CameraType.bullet,
        location="Building A - North Facade",
        lens_type=LensType.motorised,
        focal_length_min=2.8,
        focal_length_max=12.0,
        h_fov_min=28.0,
        h_fov_max=97.0,
        v_fov_min=16.0,
        v_fov_max=54.0,
        ir_cut_filter=True,
        resolution_h=2560,
        resolution_v=1440,
        megapixels=4.0,
        aspect_ratio="16:9",
        sensor_size='1/2.7"',
        sensor_type=SensorType.cmos,
        min_illumination=0.005,
        wdr=True,
        wdr_db=120.0,
        created_by=user,
    )
    await cam_model.insert()
    print(f"[+] CameraModel:    {cam_model.id}  ({cam_model.name})")

    # 4. Project
    project = Project(
        name="Seed Project",
        description="Auto-generated by seed script.",
        owner=user,
    )
    await project.insert()
    print(f"[+] Project:        {project.id}  ({project.name})")

    # 5. Camera
    cam_instance = Camera(
        project=project,
        camera_model=cam_model,
        label="CAM-01",
        lat=51.5074,
        lng=-0.1278,
        bearing=45.0,
        height=4.0,
        tilt_angle=30.0,
        focal_length_chosen=6.0,
    )
    await cam_instance.insert()
    print(f"[+] Camera: {cam_instance.id}  ({cam_instance.label})")

    # 6. Zone
    zone = Zone(
        project=project,
        label="Main Coverage Area",
        zone_type=ZoneType.coverage_area,
        geojson={
            "type": "Polygon",
            "coordinates": [[
                [-0.13, 51.50],
                [-0.12, 51.50],
                [-0.12, 51.51],
                [-0.13, 51.51],
                [-0.13, 51.50],
            ]],
        },
    )
    await zone.insert()
    print(f"[+] Zone:           {zone.id}  ({zone.label})")

    print("\nSeed complete. Check MongoDB Atlas for the above documents.")
    client.close()


if __name__ == "__main__":
    asyncio.run(seed())
