"""M1.5 seed script. Inserts one test document of each Beanie model (User, InviteToken, CameraModel, Project, CameraInstance, Zone) into MongoDB. Run: uv run python scripts/seed.py from packages/backend."""

import asyncio
import hashlib
import os
import sys
from datetime import datetime, timedelta, timezone

# Allow imports from the app package
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import motor.motor_asyncio
from beanie import init_beanie

from app.core.config import settings
from app.models.camera_instance import CameraInstance
from app.models.camera_model import CameraModel
from app.models.invite_token import InviteToken
from app.models.project import Project
from app.models.user import User, SystemRole
from app.models.zone import Zone, ZoneType


async def seed() -> None:
    client = motor.motor_asyncio.AsyncIOMotorClient(settings.MONGO_URI)
    db = client.get_default_database()
    await init_beanie(
        database=db,
        document_models=[User, InviteToken, CameraModel, Project, CameraInstance, Zone],
    )

    # 1. User
    user = User(
        email="seed@example.com",
        full_name="Seed User",
        hashed_password="$2b$12$placeholder_hash",
        system_role=SystemRole.admin,
    )
    await user.insert()
    print(f"[+] User:           {user.id}  ({user.email})")

    # 2. InviteToken
    raw_token = "seed-test-token-abc123"
    token_hash = hashlib.sha256(raw_token.encode()).hexdigest()
    invite = InviteToken(
        token_hash=token_hash,
        email="newuser@example.com",
        invited_by=user,
        expires_at=datetime.now(timezone.utc) + timedelta(hours=settings.INVITE_TOKEN_TTL_HOURS),
    )
    await invite.insert()
    print(f"[+] InviteToken:    {invite.id}")

    # 3. CameraModel
    cam_model = CameraModel(
        name="Hikvision DS-2CD2143",
        manufacturer="Hikvision",
        fov_angle=90.0,
        min_range=0.5,
        max_range=30.0,
        created_by=user,
    )
    await cam_model.insert()
    print(f"[+] CameraModel:    {cam_model.id}  ({cam_model.name})")

    # 4. Project
    project = Project(
        name="Seed Project",
        description="Auto-generated by seed script.",
        owner=user,
    )
    await project.insert()
    print(f"[+] Project:        {project.id}  ({project.name})")

    # 5. CameraInstance
    cam_instance = CameraInstance(
        project=project,
        camera_model=cam_model,
        label="CAM-01",
        lat=51.5074,
        lng=-0.1278,
        bearing=45.0,
    )
    await cam_instance.insert()
    print(f"[+] CameraInstance: {cam_instance.id}  ({cam_instance.label})")

    # 6. Zone
    zone = Zone(
        project=project,
        label="Main Coverage Area",
        zone_type=ZoneType.coverage_area,
        geojson={
            "type": "Polygon",
            "coordinates": [[
                [-0.13, 51.50],
                [-0.12, 51.50],
                [-0.12, 51.51],
                [-0.13, 51.51],
                [-0.13, 51.50],
            ]],
        },
    )
    await zone.insert()
    print(f"[+] Zone:           {zone.id}  ({zone.label})")

    print("\nSeed complete. Check MongoDB Atlas for the above documents.")
    client.close()


if __name__ == "__main__":
    asyncio.run(seed())
